import type { SandboxScene } from './sandboxStore'

export const stackedBoxesPreset: SandboxScene = {
  gravity: [0, -9.81, 0],
  items: [
    {
      id: 'preset-ground',
      shape: 'plane',
      position: [0, 0, 0],
      rotation: [-Math.PI / 2, 0, 0],
      scale: [1, 1, 1],
      size: [6, 0.02, 4],
      material: 'wood',
      color: '#d4c8a8',
      isDynamic: false,
      mass: 1,
      friction: 0.5,
      restitution: 0.3,
    },
    {
      id: 'preset-box-1',
      shape: 'box',
      position: [-0.4, 0.5, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [0.8, 0.8, 0.8],
      material: 'plastic',
      color: '#33a6b8',
      isDynamic: true,
      mass: 1,
      friction: 0.5,
      restitution: 0.2,
    },
    {
      id: 'preset-box-2',
      shape: 'box',
      position: [0.4, 1.4, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [0.7, 0.7, 0.7],
      material: 'plastic',
      color: '#dc2626',
      isDynamic: true,
      mass: 1,
      friction: 0.5,
      restitution: 0.2,
    },
  ],
}

export const slopeBallPreset: SandboxScene = {
  gravity: [0, -9.81, 0],
  items: [
    {
      id: 'preset-slope',
      shape: 'box',
      position: [0, 1.2, 0],
      rotation: [0, 0, Math.PI / 8],
      scale: [1, 1, 1],
      size: [4, 0.1, 2],
      material: 'wood',
      color: '#d4c8a8',
      isDynamic: false,
      mass: 1,
      friction: 0.4,
      restitution: 0.1,
    },
    {
      id: 'preset-ball',
      shape: 'sphere',
      position: [-1.2, 3, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [0.4, 0, 0],
      material: 'metal',
      color: '#2563eb',
      isDynamic: true,
      mass: 2,
      friction: 0.3,
      restitution: 0.6,
    },
  ],
}

export const springPendulumPreset: SandboxScene = {
  gravity: [0, -9.81, 0],
  items: [
    {
      id: 'preset-anchor',
      shape: 'box',
      position: [0, 4, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [0.4, 0.2, 0.4],
      material: 'metal',
      color: '#666666',
      isDynamic: false,
      mass: 1,
      friction: 0.5,
      restitution: 0.1,
    },
    {
      id: 'preset-spring',
      shape: 'spring',
      position: [0, 3, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [0.25, 1, 0],
      material: 'metal',
      color: '#9b9b9b',
      isDynamic: true,
      mass: 0.5,
      friction: 0.3,
      restitution: 0.2,
    },
    {
      id: 'preset-weight',
      shape: 'sphere',
      position: [0.3, 2.2, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [0.3, 0, 0],
      material: 'metal',
      color: '#ea580c',
      isDynamic: true,
      mass: 1.5,
      friction: 0.3,
      restitution: 0.4,
    },
  ],
}

export const SANDBOX_PRESETS: { id: string; label: string; scene: SandboxScene }[] = [
  { id: 'stacked-boxes', label: '堆叠方块', scene: stackedBoxesPreset },
  { id: 'slope-ball', label: '斜坡滚球', scene: slopeBallPreset },
  { id: 'spring-pendulum', label: '弹簧摆', scene: springPendulumPreset },
]
