import type { SandboxScene } from './sandboxStore'

export const stackedBoxesPreset: SandboxScene = {
  gravity: [0, -9.81, 0],
  items: [
    {
      id: 'preset-ground',
      shape: 'plane',
      position: [0, 0, 0],
      rotation: [-Math.PI / 2, 0, 0],
      scale: [1, 1, 1],
      size: [6, 0.02, 4],
      material: 'wood',
      color: '#d4c8a8',
      isDynamic: false,
      mass: 1,
      friction: 0.5,
      restitution: 0.3,
    },
    {
      id: 'preset-box-1',
      shape: 'box',
      position: [-0.4, 0.5, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [0.8, 0.8, 0.8],
      material: 'plastic',
      color: '#33a6b8',
      isDynamic: true,
      mass: 1,
      friction: 0.5,
      restitution: 0.2,
    },
    {
      id: 'preset-box-2',
      shape: 'box',
      position: [0.4, 1.4, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [0.7, 0.7, 0.7],
      material: 'plastic',
      color: '#dc2626',
      isDynamic: true,
      mass: 1,
      friction: 0.5,
      restitution: 0.2,
    },
  ],
}

export const slopeBallPreset: SandboxScene = {
  gravity: [0, -9.81, 0],
  items: [
    {
      id: 'preset-slope',
      shape: 'box',
      position: [0, 1.2, 0],
      rotation: [0, 0, Math.PI / 8],
      scale: [1, 1, 1],
      size: [4, 0.1, 2],
      material: 'wood',
      color: '#d4c8a8',
      isDynamic: false,
      mass: 1,
      friction: 0.4,
      restitution: 0.1,
    },
    {
      id: 'preset-ball',
      shape: 'sphere',
      position: [-1.2, 3, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [0.4, 0, 0],
      material: 'metal',
      color: '#2563eb',
      isDynamic: true,
      mass: 2,
      friction: 0.3,
      restitution: 0.6,
    },
  ],
}

export const springPendulumPreset: SandboxScene = {
  gravity: [0, -9.81, 0],
  items: [
    {
      id: 'preset-anchor',
      shape: 'box',
      position: [0, 4, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [0.4, 0.2, 0.4],
      material: 'metal',
      color: '#666666',
      isDynamic: false,
      mass: 1,
      friction: 0.5,
      restitution: 0.1,
    },
    {
      id: 'preset-weight',
      shape: 'sphere',
      position: [0, 2.2, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [0.3, 0, 0],
      material: 'metal',
      color: '#ea580c',
      isDynamic: true,
      mass: 1.5,
      friction: 0.3,
      restitution: 0.4,
    },
  ],
  joints: [
    {
      id: 'preset-spring-joint',
      type: 'spring',
      bodyA: 'preset-anchor',
      bodyB: 'preset-weight',
      anchorA: [0, -0.1, 0],
      anchorB: [0, 0.3, 0],
      restLength: 1.6,
      stiffness: 80,
      damping: 3,
    },
  ],
}

export const collisionPreset: SandboxScene = {
  gravity: [0, -9.81, 0],
  items: [
    {
      id: 'preset-ground',
      shape: 'plane',
      position: [0, 0, 0],
      rotation: [-Math.PI / 2, 0, 0],
      scale: [1, 1, 1],
      size: [10, 0.02, 8],
      material: 'wood',
      color: '#d4c8a8',
      isDynamic: false,
      mass: 1,
      friction: 0.5,
      restitution: 0.3,
    },
    {
      id: 'preset-ball-1',
      shape: 'sphere',
      position: [-2, 1, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [0.5, 0, 0],
      material: 'metal',
      color: '#dc2626',
      isDynamic: true,
      mass: 2,
      friction: 0.2,
      restitution: 0.8,
    },
    {
      id: 'preset-ball-2',
      shape: 'sphere',
      position: [2, 1, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [0.5, 0, 0],
      material: 'metal',
      color: '#2563eb',
      isDynamic: true,
      mass: 2,
      friction: 0.2,
      restitution: 0.8,
    },
  ],
}

export const newtonCradlePreset: SandboxScene = {
  gravity: [0, -9.81, 0],
  items: [
    {
      id: 'preset-frame-top',
      shape: 'box',
      position: [0, 3, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [3, 0.1, 0.4],
      material: 'metal',
      color: '#666666',
      isDynamic: false,
      mass: 1,
      friction: 0.5,
      restitution: 0.1,
    },
    ...Array.from({ length: 5 }, (_, i) => {
      const x = -1 + i * 0.5
      return {
        id: `preset-ball-${i}`,
        shape: 'sphere' as const,
        position: [x, 2, 0] as [number, number, number],
        rotation: [0, 0, 0] as [number, number, number],
        scale: [1, 1, 1] as [number, number, number],
        size: [0.2, 0, 0] as [number, number, number],
        material: 'metal' as const,
        color: '#9ca3af',
        isDynamic: true,
        mass: 0.5,
        friction: 0.1,
        restitution: 0.95,
      }
    }),
  ],
  joints: Array.from({ length: 5 }, (_, i) => ({
    id: `preset-rope-${i}`,
    type: 'rope' as const,
    bodyA: 'preset-frame-top',
    bodyB: `preset-ball-${i}`,
    anchorA: [-1 + i * 0.5, -0.05, 0] as [number, number, number],
    anchorB: [0, 0.2, 0] as [number, number, number],
    maxDistance: 0.8,
  })),
}

export const rampPreset: SandboxScene = {
  gravity: [0, -9.81, 0],
  items: [
    {
      id: 'preset-ground',
      shape: 'plane',
      position: [0, 0, 0],
      rotation: [-Math.PI / 2, 0, 0],
      scale: [1, 1, 1],
      size: [10, 0.02, 8],
      material: 'wood',
      color: '#d4c8a8',
      isDynamic: false,
      mass: 1,
      friction: 0.5,
      restitution: 0.3,
    },
    {
      id: 'preset-ramp',
      shape: 'box',
      position: [0, 1, 0],
      rotation: [0, 0, Math.PI / 6],
      scale: [1, 1, 1],
      size: [5, 0.15, 3],
      material: 'wood',
      color: '#a08866',
      isDynamic: false,
      mass: 1,
      friction: 0.3,
      restitution: 0.1,
    },
    {
      id: 'preset-cube',
      shape: 'box',
      position: [-1.5, 2.5, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      size: [0.5, 0.5, 0.5],
      material: 'plastic',
      color: '#33a6b8',
      isDynamic: true,
      mass: 1,
      friction: 0.2,
      restitution: 0.2,
    },
  ],
}

export const SANDBOX_PRESETS: { id: string; label: string; labelKey: string; scene: SandboxScene }[] = [
  { id: 'stacked-boxes', label: '堆叠方块', labelKey: 'sandbox.presets.stackedBoxes', scene: stackedBoxesPreset },
  { id: 'slope-ball', label: '斜坡滚球', labelKey: 'sandbox.presets.slopeBall', scene: slopeBallPreset },
  { id: 'spring-pendulum', label: '弹簧摆', labelKey: 'sandbox.presets.springPendulum', scene: springPendulumPreset },
  { id: 'collision', label: '双球碰撞', labelKey: 'sandbox.presets.collision', scene: collisionPreset },
  { id: 'newton-cradle', label: '牛顿摆', labelKey: 'sandbox.presets.newtonCradle', scene: newtonCradlePreset },
  { id: 'ramp', label: '斜面下滑', labelKey: 'sandbox.presets.ramp', scene: rampPreset },
]
