import type { Recipe } from './recipeTypes'
import type { SandboxItem } from '@/features/sandbox/sandboxStore'

function groundPlane(): SandboxItem {
  return {
    id: 'recipe-ground',
    shape: 'plane',
    position: [0, 0, 0],
    rotation: [-Math.PI / 2, 0, 0],
    scale: [1, 1, 1],
    size: [10, 0.02, 8],
    material: 'wood',
    color: '#d4c8a8',
    isDynamic: false,
    mass: 1,
    friction: 0.5,
    restitution: 0.3,
  }
}

export const RECIPE_LIBRARY: Recipe[] = [
  // ===== Mechanics =====
  {
    id: 'recipe-free-fall',
    title: 'recipe.freeFall.title',
    description: 'recipe.freeFall.description',
    category: 'mechanics',
    difficulty: 'beginner',
    tags: ['gravity', 'acceleration', 'kinematics'],
    learningObjectives: ['recipe.freeFall.objective1', 'recipe.freeFall.objective2'],
    scene: {
      gravity: [0, -9.81, 0],
      items: [
        groundPlane(),
        {
          id: 'recipe-ball',
          shape: 'sphere',
          position: [0, 5, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [0.4, 0, 0],
          material: 'metal',
          color: '#2563eb',
          isDynamic: true,
          mass: 1,
          friction: 0.2,
          restitution: 0.3,
        },
      ],
    },
    steps: [
      {
        title: 'recipe.freeFall.step1.title',
        description: 'recipe.freeFall.step1.desc',
        hint: 'recipe.freeFall.step1.hint',
      },
      {
        title: 'recipe.freeFall.step2.title',
        description: 'recipe.freeFall.step2.desc',
        hint: 'recipe.freeFall.step2.hint',
        setupDescription: 'recipe.freeFall.step2.setup',
      },
      {
        title: 'recipe.freeFall.step3.title',
        description: 'recipe.freeFall.step3.desc',
        hint: 'recipe.freeFall.step3.hint',
      },
    ],
  },
  {
    id: 'recipe-pendulum',
    title: 'recipe.pendulum.title',
    description: 'recipe.pendulum.description',
    category: 'mechanics',
    difficulty: 'beginner',
    tags: ['pendulum', 'periodic', 'oscillation'],
    learningObjectives: ['recipe.pendulum.objective1', 'recipe.pendulum.objective2'],
    scene: {
      gravity: [0, -9.81, 0],
      items: [
        groundPlane(),
        {
          id: 'recipe-frame',
          shape: 'box',
          position: [0, 3.5, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [0.4, 0.2, 0.4],
          material: 'metal',
          color: '#666666',
          isDynamic: false,
          mass: 1,
          friction: 0.5,
          restitution: 0.1,
        },
        {
          id: 'recipe-bob',
          shape: 'sphere',
          position: [1.2, 1.5, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [0.3, 0, 0],
          material: 'metal',
          color: '#ea580c',
          isDynamic: true,
          mass: 1,
          friction: 0.2,
          restitution: 0.2,
        },
      ],
      joints: [
        {
          id: 'recipe-rope',
          type: 'rope',
          bodyA: 'recipe-frame',
          bodyB: 'recipe-bob',
          anchorA: [0, -0.1, 0],
          anchorB: [0, 0.2, 0],
          maxDistance: 2,
        },
      ],
    },
    steps: [
      {
        title: 'recipe.pendulum.step1.title',
        description: 'recipe.pendulum.step1.desc',
        hint: 'recipe.pendulum.step1.hint',
        setupDescription: 'recipe.pendulum.step1.setup',
      },
      {
        title: 'recipe.pendulum.step2.title',
        description: 'recipe.pendulum.step2.desc',
        hint: 'recipe.pendulum.step2.hint',
      },
      {
        title: 'recipe.pendulum.step3.title',
        description: 'recipe.pendulum.step3.desc',
        hint: 'recipe.pendulum.step3.hint',
      },
    ],
  },
  {
    id: 'recipe-ramp',
    title: 'recipe.ramp.title',
    description: 'recipe.ramp.description',
    category: 'mechanics',
    difficulty: 'intermediate',
    tags: ['inclined-plane', 'acceleration', 'friction'],
    learningObjectives: ['recipe.ramp.objective1', 'recipe.ramp.objective2'],
    scene: {
      gravity: [0, -9.81, 0],
      items: [
        groundPlane(),
        {
          id: 'recipe-ramp',
          shape: 'slope',
          position: [0, 0.6, 0],
          rotation: [0, 0, Math.PI / 6],
          scale: [1, 1, 1],
          size: [4, 0.1, 2],
          material: 'wood',
          color: '#d4c8a8',
          isDynamic: false,
          mass: 1,
          friction: 0.2,
          restitution: 0.1,
        },
        {
          id: 'recipe-cart',
          shape: 'box',
          position: [-1.4, 2.3, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [0.4, 0.4, 0.4],
          material: 'plastic',
          color: '#33a6b8',
          isDynamic: true,
          mass: 1,
          friction: 0.15,
          restitution: 0.1,
        },
      ],
    },
    steps: [
      {
        title: 'recipe.ramp.step1.title',
        description: 'recipe.ramp.step1.desc',
        hint: 'recipe.ramp.step1.hint',
        setupDescription: 'recipe.ramp.step1.setup',
      },
      {
        title: 'recipe.ramp.step2.title',
        description: 'recipe.ramp.step2.desc',
        hint: 'recipe.ramp.step2.hint',
      },
      {
        title: 'recipe.ramp.step3.title',
        description: 'recipe.ramp.step3.desc',
        hint: 'recipe.ramp.step3.hint',
      },
    ],
  },
  {
    id: 'recipe-collision',
    title: 'recipe.collision.title',
    description: 'recipe.collision.description',
    category: 'mechanics',
    difficulty: 'intermediate',
    tags: ['collision', 'momentum', 'elastic', 'inelastic'],
    learningObjectives: ['recipe.collision.objective1', 'recipe.collision.objective2'],
    scene: {
      gravity: [0, -9.81, 0],
      items: [
        groundPlane(),
        {
          id: 'recipe-ball-a',
          shape: 'sphere',
          position: [-2, 2, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [0.5, 0, 0],
          material: 'metal',
          color: '#dc2626',
          isDynamic: true,
          mass: 2,
          friction: 0.1,
          restitution: 0.9,
        },
        {
          id: 'recipe-ball-b',
          shape: 'sphere',
          position: [2, 2, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [0.35, 0, 0],
          material: 'plastic',
          color: '#2563eb',
          isDynamic: true,
          mass: 0.5,
          friction: 0.1,
          restitution: 0.9,
        },
      ],
    },
    steps: [
      {
        title: 'recipe.collision.step1.title',
        description: 'recipe.collision.step1.desc',
        hint: 'recipe.collision.step1.hint',
        setupDescription: 'recipe.collision.step1.setup',
      },
      {
        title: 'recipe.collision.step2.title',
        description: 'recipe.collision.step2.desc',
        hint: 'recipe.collision.step2.hint',
      },
      {
        title: 'recipe.collision.step3.title',
        description: 'recipe.collision.step3.desc',
        hint: 'recipe.collision.step3.hint',
      },
    ],
  },

  // ===== Electromagnetism =====
  {
    id: 'recipe-force-field',
    title: 'recipe.forceField.title',
    description: 'recipe.forceField.description',
    category: 'electromagnetism',
    difficulty: 'intermediate',
    tags: ['force-field', 'gravity', 'inverse-square'],
    learningObjectives: ['recipe.forceField.objective1', 'recipe.forceField.objective2'],
    scene: {
      gravity: [0, -9.81, 0],
      items: [
        groundPlane(),
        {
          id: 'recipe-field-source',
          shape: 'force_field',
          position: [0, 3, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [1, 1, 1],
          material: 'metal',
          color: '#7c3aed',
          isDynamic: false,
          mass: 1,
          friction: 0.5,
          restitution: 0.3,
        },
        {
          id: 'recipe-test-particle',
          shape: 'sphere',
          position: [2, 3, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [0.2, 0, 0],
          material: 'plastic',
          color: '#f59e0b',
          isDynamic: true,
          mass: 0.1,
          friction: 0.1,
          restitution: 0.3,
        },
      ],
    },
    steps: [
      {
        title: 'recipe.forceField.step1.title',
        description: 'recipe.forceField.step1.desc',
        hint: 'recipe.forceField.step1.hint',
        setupDescription: 'recipe.forceField.step1.setup',
      },
      {
        title: 'recipe.forceField.step2.title',
        description: 'recipe.forceField.step2.desc',
        hint: 'recipe.forceField.step2.hint',
      },
      {
        title: 'recipe.forceField.step3.title',
        description: 'recipe.forceField.step3.desc',
        hint: 'recipe.forceField.step3.hint',
      },
    ],
  },

  // ===== Thermodynamics =====
  {
    id: 'recipe-thermal',
    title: 'recipe.thermal.title',
    description: 'recipe.thermal.description',
    category: 'thermodynamics',
    difficulty: 'advanced',
    tags: ['heat', 'temperature', 'conduction'],
    learningObjectives: ['recipe.thermal.objective1', 'recipe.thermal.objective2'],
    scene: {
      gravity: [0, -9.81, 0],
      items: [
        groundPlane(),
        {
          id: 'recipe-hot',
          shape: 'box',
          position: [-1.5, 2, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [0.5, 0.5, 0.5],
          material: 'metal',
          color: '#dc2626',
          isDynamic: false,
          mass: 1,
          friction: 0.5,
          restitution: 0.1,
        },
        {
          id: 'recipe-cold',
          shape: 'box',
          position: [1.5, 2, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [0.5, 0.5, 0.5],
          material: 'plastic',
          color: '#2563eb',
          isDynamic: false,
          mass: 1,
          friction: 0.5,
          restitution: 0.1,
        },
        {
          id: 'recipe-bridge',
          shape: 'box',
          position: [0, 2, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [2, 0.1, 0.3],
          material: 'metal',
          color: '#9ca3af',
          isDynamic: false,
          mass: 0.5,
          friction: 0.5,
          restitution: 0.1,
        },
      ],
    },
    steps: [
      {
        title: 'recipe.thermal.step1.title',
        description: 'recipe.thermal.step1.desc',
        hint: 'recipe.thermal.step1.hint',
        setupDescription: 'recipe.thermal.step1.setup',
      },
      {
        title: 'recipe.thermal.step2.title',
        description: 'recipe.thermal.step2.desc',
        hint: 'recipe.thermal.step2.hint',
      },
      {
        title: 'recipe.thermal.step3.title',
        description: 'recipe.thermal.step3.desc',
        hint: 'recipe.thermal.step3.hint',
      },
    ],
  },

  // ===== Optics =====
  {
    id: 'recipe-optics',
    title: 'recipe.optics.title',
    description: 'recipe.optics.description',
    category: 'optics',
    difficulty: 'beginner',
    tags: ['reflection', 'light', 'ray'],
    learningObjectives: ['recipe.optics.objective1', 'recipe.optics.objective2'],
    scene: {
      gravity: [0, 0, 0],
      items: [
        {
          id: 'recipe-mirror',
          shape: 'plane',
          position: [0, 2, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [3, 0.02, 2],
          material: 'glass',
          color: '#93c5fd',
          isDynamic: false,
          mass: 1,
          friction: 0.5,
          restitution: 0.3,
        },
        {
          id: 'recipe-light-source',
          shape: 'sphere',
          position: [-3, 2, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [0.2, 0, 0],
          material: 'metal',
          color: '#fbbf24',
          isDynamic: false,
          mass: 1,
          friction: 0.5,
          restitution: 0.3,
        },
      ],
    },
    steps: [
      {
        title: 'recipe.optics.step1.title',
        description: 'recipe.optics.step1.desc',
        hint: 'recipe.optics.step1.hint',
        setupDescription: 'recipe.optics.step1.setup',
      },
      {
        title: 'recipe.optics.step2.title',
        description: 'recipe.optics.step2.desc',
        hint: 'recipe.optics.step2.hint',
      },
    ],
  },

  // ===== Waves =====
  {
    id: 'recipe-waves',
    title: 'recipe.waves.title',
    description: 'recipe.waves.description',
    category: 'waves',
    difficulty: 'intermediate',
    tags: ['wave', 'oscillation', 'frequency'],
    learningObjectives: ['recipe.waves.objective1', 'recipe.waves.objective2'],
    scene: {
      gravity: [0, -9.81, 0],
      items: [
        groundPlane(),
        {
          id: 'recipe-spring-mass',
          shape: 'sphere',
          position: [0, 3, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [0.3, 0, 0],
          material: 'metal',
          color: '#ea580c',
          isDynamic: true,
          mass: 1,
          friction: 0.1,
          restitution: 0.1,
        },
        {
          id: 'recipe-anchor',
          shape: 'box',
          position: [0, 5, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          size: [0.3, 0.2, 0.3],
          material: 'metal',
          color: '#666666',
          isDynamic: false,
          mass: 1,
          friction: 0.5,
          restitution: 0.1,
        },
      ],
      joints: [
        {
          id: 'recipe-spring',
          type: 'spring',
          bodyA: 'recipe-anchor',
          bodyB: 'recipe-spring-mass',
          anchorA: [0, 0, 0],
          anchorB: [0, 0.2, 0],
          restLength: 1.5,
          stiffness: 100,
          damping: 5,
        },
      ],
    },
    steps: [
      {
        title: 'recipe.waves.step1.title',
        description: 'recipe.waves.step1.desc',
        hint: 'recipe.waves.step1.hint',
        setupDescription: 'recipe.waves.step1.setup',
      },
      {
        title: 'recipe.waves.step2.title',
        description: 'recipe.waves.step2.desc',
        hint: 'recipe.waves.step2.hint',
      },
      {
        title: 'recipe.waves.step3.title',
        description: 'recipe.waves.step3.desc',
        hint: 'recipe.waves.step3.hint',
      },
    ],
  },
]

export function getRecipeById(id: string): Recipe | undefined {
  return RECIPE_LIBRARY.find((r) => r.id === id)
}

export function getRecipesByCategory(category: string): Recipe[] {
  return RECIPE_LIBRARY.filter((r) => r.category === category)
}
